version: '3.8'

services:
  backend: '
    image: nginx:latest
    container_name: nginx-backend
    ports:
      - "80:80"
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

  frontend:
    image: tomcat:9.0
    container_name: tomcat-frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/webapps:/usr/local/tomcat/webapps
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_NAME=studentdb
      - DB_USER=root
      - DB_PASSWORD=my-secret-pw
    networks:
      - app-network

  database:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
       MYSQL_DATABASE=studentdb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
   mariadb_data:
